# Generated by Django 5.1.2 on 2024-10-30 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='zine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='uploader.zine'),
        ),
    ]
