# Generated by Django 5.1.2 on 2024-12-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_alter_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='zine',
            name='layout',
            field=models.CharField(choices=[('T4', '4p Single fold vertical, one-side print, Portrait'), ('TC8', '8p Traditional inner-cut, single-side print, Landscape')], default='T4', max_length=4),
        ),
        migrations.AddField(
            model_name='zine',
            name='sheet',
            field=models.CharField(choices=[('A4', 'A4, Europe'), ('Lt', 'US Letter (8.5x11in)'), ('Lg', 'US Legal (8.5x14in)'), ('Tb', 'US Tabloid (11x17in)')], default='Lt', max_length=4),
        ),
    ]
