# Generated by Django 5.1.2 on 2024-12-21 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_zine_layout_zine_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='zine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='uploader.zine'),
        ),
    ]
